#!/bin/bash
# Baseline existing database with Prisma Migrate
# This script creates the initial migration and marks it as applied

set -e

echo "=== BASELINING DATABASE WITH PRISMA MIGRATE ==="

# Create migrations directory if it doesn't exist
mkdir -p prisma/migrations

# Generate initial migration
echo "1. Generating initial migration..."
DATABASE_URL="postgresql://chozengone@localhost:5432/renovation_advisor" \
npx prisma migrate diff \
  --from-empty \
  --to-schema-datamodel=./prisma/schema.prisma \
  --script > prisma/migrations/initial_baseline.sql

# Create migration directory with timestamp
MIGRATION_DIR="prisma/migrations/$(date +%Y%m%d%H%M%S)_initial_baseline"
mkdir -p "$MIGRATION_DIR"

# Move SQL file to migration directory
mv prisma/migrations/initial_baseline.sql "$MIGRATION_DIR/migration.sql"

# Create migration.toml file
cat > "$MIGRATION_DIR/migration.toml" << EOF
# Migration generated by Prisma
# This is a baseline migration for an existing database

# The database was already in sync with this schema
# This migration is marked as applied to baseline the database
EOF

echo "2. Migration created at: $MIGRATION_DIR"

# Mark migration as applied
echo "3. Marking migration as applied..."
DATABASE_URL="postgresql://chozengone@localhost:5432/renovation_advisor" \
npx prisma migrate resolve \
  --applied "$(basename "$MIGRATION_DIR")" \
  --schema=./prisma/schema.prisma

echo "4. Verifying migration status..."
DATABASE_URL="postgresql://chozengone@localhost:5432/renovation_advisor" \
npx prisma migrate status --schema=./prisma/schema.prisma

echo ""
echo "✅ Database baselining complete!"
echo "The database is now managed by Prisma Migrate."
echo ""
echo "Next steps:"
echo "1. Run 'npx prisma generate' to update client"
echo "2. Test that all queries still work"
echo "3. Future schema changes should use 'npx prisma migrate dev'"